name: food_delivery_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  hexcolor: ^2.0.6  
  flutter_svg: ^0.22.0
  connectivity_plus: ^2.3.6+1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  flutter_image_compress: ^1.0.0-nullsafety
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
  #  - assets/icons/

  fonts:
    - family: Nunito-italic
      fonts:
        - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf

    - family: Nunito-SemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf  

    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf  

    - family: Nunito-ExtraBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf 

    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf 

    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf 

    

        

